spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    initialmicro:
      path: /initialmicro/**
      url: http://localhost:8082/



jwt:
  secret: Vetri1@3$5^7*9)


logging:
  kafka:
    bootstrap:
      server:  localhost:9092


management:
  endpoints:
    web:
      exposure:
        include : httptrace

